-- =====================================================================
-- AI DISASTER EMERGENCY PORTAL - PRODUCTION SUPABASE SCHEMAS (CLEAN DDL)
-- Paste and run this script in Supabase SQL Editor:
-- https://supabase.com/dashboard/project/_/sql/new
-- =====================================================================

-- 1. DROP EXISTING TABLES IF RE-CREATING
DROP TABLE IF EXISTS activity_logs CASCADE;
DROP TABLE IF EXISTS notifications CASCADE;
DROP TABLE IF EXISTS resources CASCADE;
DROP TABLE IF EXISTS relief_centers CASCADE;
DROP TABLE IF EXISTS emergency_reports CASCADE;
DROP TABLE IF EXISTS volunteers CASCADE;
DROP TABLE IF EXISTS users CASCADE;

-- 2. CREATE USERS TABLE
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'citizen', -- citizen, volunteer, officer, ngo, admin
    phone TEXT,
    lat DOUBLE PRECISION DEFAULT 28.6139,
    lng DOUBLE PRECISION DEFAULT 77.2090,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 3. CREATE VOLUNTEERS TABLE
CREATE TABLE volunteers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    name TEXT,
    email TEXT,
    phone TEXT,
    status TEXT DEFAULT 'pending', -- pending, verified, rejected
    skills TEXT[] DEFAULT ARRAY['Medical First-Aid', 'Rescue Swimming'],
    availability BOOLEAN DEFAULT TRUE,
    completed_missions INT DEFAULT 0,
    performance_score DOUBLE PRECISION DEFAULT 5.0,
    certificate_url TEXT
);

-- 4. CREATE EMERGENCY REPORTS TABLE
CREATE TABLE emergency_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    user_name TEXT DEFAULT 'Citizen SOS User',
    disaster_type TEXT NOT NULL, -- Flood, Fire, Earthquake, Cyclone, Heatwave, Landslide, Medical Emergency
    description TEXT NOT NULL,
    lat DOUBLE PRECISION NOT NULL,
    lng DOUBLE PRECISION NOT NULL,
    location_name TEXT DEFAULT 'Disaster Emergency Sector',
    people_affected INT DEFAULT 1,
    urgency TEXT DEFAULT 'High', -- Low, Medium, High, Critical
    ai_severity INT DEFAULT 5, -- 1-10 scale
    ai_category TEXT DEFAULT 'General Emergency Triage',
    ai_recommended_team TEXT DEFAULT 'NDRF Fast Response Team',
    ai_summary TEXT,
    status TEXT DEFAULT 'Pending', -- Pending, Assigned, In Progress, Resolved, Cancelled
    assigned_team TEXT,
    image_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 5. CREATE RELIEF CENTERS TABLE
CREATE TABLE relief_centers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    location_name TEXT NOT NULL,
    lat DOUBLE PRECISION NOT NULL,
    lng DOUBLE PRECISION NOT NULL,
    capacity INT DEFAULT 500,
    current_occupancy INT DEFAULT 0,
    available_beds INT DEFAULT 500,
    medical_staff INT DEFAULT 0,
    food_stock_days INT DEFAULT 0,
    water_stock_days INT DEFAULT 0,
    medicines TEXT DEFAULT 'Adequate',
    generator_status TEXT DEFAULT 'Operational',
    contact_phone TEXT DEFAULT '+91 1800-112-911'
);

-- 6. CREATE RESOURCES TABLE
CREATE TABLE resources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner TEXT DEFAULT 'District Disaster Management Authority',
    item_type TEXT NOT NULL,
    quantity INT DEFAULT 0,
    unit TEXT DEFAULT 'Units',
    lat DOUBLE PRECISION DEFAULT 28.6139,
    lng DOUBLE PRECISION DEFAULT 77.2090,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 7. CREATE NOTIFICATIONS TABLE
CREATE TABLE notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    message TEXT NOT NULL,
    type TEXT DEFAULT 'info', -- urgent, warning, info
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 8. CREATE ACTIVITY LOGS TABLE
CREATE TABLE activity_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action TEXT NOT NULL,
    performed_by TEXT NOT NULL,
    details TEXT,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- ROW LEVEL SECURITY (RLS) POLICIES
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE volunteers ENABLE ROW LEVEL SECURITY;
ALTER TABLE emergency_reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE relief_centers ENABLE ROW LEVEL SECURITY;
ALTER TABLE resources ENABLE ROW LEVEL SECURITY;
ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE activity_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public Read Access" ON emergency_reports FOR SELECT USING (true);
CREATE POLICY "Public Insert Access" ON emergency_reports FOR INSERT WITH CHECK (true);
CREATE POLICY "Public Update Access" ON emergency_reports FOR UPDATE USING (true);

CREATE POLICY "Public Read Relief Centers" ON relief_centers FOR SELECT USING (true);
CREATE POLICY "Public Read Resources" ON resources FOR SELECT USING (true);
CREATE POLICY "Public Read Volunteers" ON volunteers FOR SELECT USING (true);
CREATE POLICY "Public Read Notifications" ON notifications FOR SELECT USING (true);
